# -*- coding: utf-8 -*-
"""pytorch mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqceaMjK9urGazcvLWtzQwg4lZRZK2Q0
"""

from google.colab import files
uploaded=files.upload()

#importing libraries
!pip install idx2numpy
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
# Import idx2numpy
import idx2numpy

import zipfile
#extracting file data from zip file
with zipfile.ZipFile("MNIST_ORG.zip",'r') as zip_ref:
  zip_ref.extractall("mnist_data")
import os
os.listdir("mnist_data")
#converting idx datafile into numpy file
images=idx2numpy.convert_from_file("mnist_data/train-images.idx3-ubyte")
labels=idx2numpy.convert_from_file('mnist_data/train-labels.idx1-ubyte')
timages=idx2numpy.convert_from_file('mnist_data/t10k-images.idx3-ubyte')
tlabels=idx2numpy.convert_from_file('mnist_data/t10k-labels.idx1-ubyte')

#convert numpyarray into tensor and scaling features
images = torch.tensor(images / 255.0, dtype=torch.float32).unsqueeze(1)
labels = torch.tensor(labels, dtype=torch.long)
timages=torch.tensor(timages/255.0,dtype=torch.float32).unsqueeze(1)
tlabels=torch.tensor(tlabels,dtype=torch.long)

#standarise the dataset
mean, std = images.mean(), images.std()

images = (images - mean) / std
timages = (timages - mean) / std

torch.manual_seed(42)
#setting up device to cuda

device=torch.device('cuda'if torch.cuda.is_available() else 'cpu')
 #creating custom dataset
class customdataset(Dataset):
  def __init__(self,features,labels):
    self.features=torch.tensor(features,dtype=torch.float32)
    self.labels=torch.tensor(labels,dtype=torch.long)
  def __getitem__(self,index):
    return self.features[index],self.labels[index]
  def __len__(self):
    return len(self.features)

traindataset=customdataset(images,labels)
testdataset=customdataset(timages,tlabels)

#loading the dataset and assigning batch size
trainloader=DataLoader(traindataset,batch_size=128,shuffle=True ,pin_memory=True)
testloader=DataLoader(testdataset,batch_size=128,shuffle=False, pin_memory=True)

#creating the nn network
class one_layer_nn(nn.Module):
  def __init__(self ,num_features):
    super().__init__()
    self.flatten=nn.Flatten()
    self.linear_relu_stack=nn.Sequential(
        nn.Linear(num_features,256),
        nn.BatchNorm1d(256),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(256,10)
    )
  def forward(self,x):
    x = self.flatten(x)
    return self.linear_relu_stack(x)
#initialising parameters
learning_rate=0.001
epoches=50

#creating model
model=one_layer_nn(images.shape[2]*images.shape[3])
model=model.to(device)

#loss function defined
loss_fn=nn.CrossEntropyLoss(label_smoothing= 0.1)

#using optimization technique ADAM (could have used momentum ,SGD , RMS prop but found it working better)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate , weight_decay=1e-5)

train_losses = []
train_accuracies = []

#starting training model
for epoch in range(epoches):
  total_epoch_loss=0
  correct=0
  total=0
  for batch_features,batch_labels in trainloader:
    batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
    #getting prediction from model(forward propogation)
    pred=model(batch_features)
    #calculating loss
    loss=loss_fn(pred,batch_labels)
     # zero out gradient
    optimizer.zero_grad()
    #backpropogation
    loss.backward()
    #this i also don't know the use , just found it as a solution to overcome 'exploding gradient' problem
    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
     #call to use optimising technique and updating parameters
    optimizer.step()
     #calculating loss and accuracy
    total_epoch_loss+=loss.item()
    correct += (torch.argmax(pred,dim=1) == batch_labels).sum().item()
    total += batch_labels.size(0)
  acc=100.*correct/total
  avg_epoch_loss=total_epoch_loss/len(trainloader)
  train_losses.append(avg_epoch_loss)
  train_accuracies.append(acc)
  print(f"Epoch {epoch+1}/{epoches}, Loss: {avg_epoch_loss:.4f}, accuracy:{acc:.2f}%")

#it is a call to tell that model will now be evaluated on test set
model.eval()

tcorrect=0
ttotal=0
tloss=0
#taking 10 images from test data for prediction
simages, slabels = next(iter(testloader))
simages, slabels = images[:10], labels[:10]
simages = simages.to(device)

with torch.no_grad():
  for batch_features,batch_labels in testloader:
    batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
    output=model(batch_features)
    loss=loss_fn(output,batch_labels)
    tloss+=loss.item()
    tcorrect+=(torch.argmax(output,dim=1)==batch_labels).sum().item()
    ttotal+=batch_labels.size(0)
avg_test_loss=tloss/len(testloader)
tacc=100.*tcorrect/ttotal

print(f"Test loss : {avg_test_loss:.4f}, Accuracy: {tacc:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

# Plot loss
plt.subplot(1, 2, 1)
plt.plot(train_losses, label="Training Loss", color='blue')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss Curve")
plt.legend()

# Plot accuracy
plt.subplot(1, 2, 2)
plt.plot(train_accuracies, label="Training Accuracy", color='green')
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training Accuracy Curve")
plt.legend()

plt.show()

model.eval()
with torch.no_grad():
    soutputs = model(simages)
    _, spreds = soutputs.max(1)

simages = simages.cpu()
spreds = spreds.cpu()
slabels = slabels.cpu()

fig, axes = plt.subplots(5, 5, figsize=(10, 10))
fig.suptitle('MNIST Predictions (first 10 test images)', fontsize=16)

for i in range(25):
    ax = axes[i // 5, i % 5]
    ax.axis('off')

    if i < 10:
        img = simages[i].squeeze(0)
        ax.imshow(img, cmap='gray')
        ax.set_title(f"Pred: {spreds[i]}\nTrue: {slabels[i]}")

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

plt.subplot(1, 2, 2)
plt.plot(train_accuracies, label="Training Accuracy", color='green')
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training Accuracy Curve")
plt.legend()

#importing libraries
!pip install idx2numpy
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import idx2numpy # Import idx2numpy

import zipfile
#extracting file data from zip file
with zipfile.ZipFile("MNIST_ORG.zip",'r') as zip_ref:
  zip_ref.extractall("mnist_data")
import os
os.listdir("mnist_data")
#converting idx datafile into numpy file
images=idx2numpy.convert_from_file("mnist_data/train-images.idx3-ubyte")
labels=idx2numpy.convert_from_file('mnist_data/train-labels.idx1-ubyte')
timages=idx2numpy.convert_from_file('mnist_data/t10k-images.idx3-ubyte')
tlabels=idx2numpy.convert_from_file('mnist_data/t10k-labels.idx1-ubyte')

print(len(images),len(labels),len(timages),len(tlabels))

#convert numpyarray into tensor and scaling features
images = torch.tensor(images / 255.0, dtype=torch.float32).unsqueeze(1)
labels = torch.tensor(labels, dtype=torch.long)
timages=torch.tensor(timages/255.0,dtype=torch.float32).unsqueeze(1)
tlabels=torch.tensor(tlabels,dtype=torch.long)

mean,std=images.mean(),images.std()

# Standardize
images = (images - mean) / std
timages = (timages - mean) / std

torch.manual_seed(42)

device=torch.device('cuda'if torch.cuda.is_available() else 'cpu')

class customdataset(Dataset):
  def __init__(self,features,labels):
    # Features are already tensors from the conversion above, avoid re-converting
    self.features=features
    self.labels=labels
  def __getitem__(self,index):
    return self.features[index],self.labels[index]
  def __len__(self):
    return len(self.features)

traindataset=customdataset(images,labels)
testdataset=customdataset(timages,tlabels)

trainloader=DataLoader(traindataset,batch_size=64,shuffle=True ,pin_memory=True)
testloader=DataLoader(testdataset,batch_size=64,shuffle=False, pin_memory=True)

# Two-layer NN
class two_layer_nn(nn.Module):
  def __init__(self ,num_features):
    super().__init__()
    self.flatten=nn.Flatten()
    self.linear_relu_stack=nn.Sequential(
        nn.Linear(num_features,512),  # First hidden layer
        nn.BatchNorm1d(512),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(512,256), # Second hidden layer
        nn.BatchNorm1d(256),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(256,10)
    )
  def forward(self,x):
    x = self.flatten(x)
    return self.linear_relu_stack(x)

learning_rate=0.001
epoches=20


model=two_layer_nn(images.shape[2]*images.shape[3])
model=model.to(device)
loss_fn=nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate , weight_decay=1e-6)

train_losses = []
train_accuracies = []

for epoch in range(epoches):
  total_epoch_loss=0
  correct=0
  total=0
  for batch_features,batch_labels in trainloader:
    batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
    pred=model(batch_features)
    loss=loss_fn(pred,batch_labels)
    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
    optimizer.step()
    total_epoch_loss+=loss.item()
    _, predicted = pred.max(1)
    correct += (predicted == batch_labels).sum().item()
    total += batch_labels.size(0)
  acc=100.*correct/total
  avg_epoch_loss=total_epoch_loss/len(trainloader)
  train_losses.append(avg_epoch_loss)
  train_accuracies.append(acc)
  print(f"Epoch {epoch+1}/{epoches}, Loss: {avg_epoch_loss:.4f}, accuracy:{acc:.2f}%")

model.eval()

tcorrect=0
ttotal=0
tloss=0
# Get a batch of images for visualization from the test set
simages_vis, slabels_vis = next(iter(testloader))
# Take the first 10 images from this batch for visualization
simages_vis = simages_vis[:10]
slabels_vis = slabels_vis[:10]
simages_vis = simages_vis.to(device)


with torch.no_grad():
  for batch_features,batch_labels in testloader:
    batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
    ouput=model(batch_features)
    loss=loss_fn(ouput,batch_labels)
    _,predicted=ouput.max(1)
    tloss+=loss.item()
    tcorrect+=(predicted==batch_labels).sum().item()
    ttotal+=batch_labels.size(0)
avg_test_loss=tloss/len(testloader)
tacc=100.*tcorrect/ttotal

print(f"Test loss : {avg_test_loss:.4f}, Accuracy: {tacc:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

# Plot loss
plt.subplot(1, 2, 1)
plt.plot(train_losses, label="Training Loss", color='blue')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss Curve")
plt.legend()

# Plot accuracy
plt.subplot(1, 2, 2)
plt.plot(train_accuracies, label="Training Accuracy", color='green')
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training Accuracy Curve")
plt.legend()

plt.show()

model.eval()
with torch.no_grad():
    soutputs = model(simages_vis) # Use simages_vis here
    _, spreds = soutputs.max(1)

simages_vis = simages_vis.cpu()
spreds = spreds.cpu()
slabels_vis = slabels_vis.cpu()

fig, axes = plt.subplots(2, 5, figsize=(12, 5)) # Adjusted for 10 images
fig.suptitle('MNIST Predictions (first 10 test images)', fontsize=16)

for i in range(10): # Loop through 10 images
    ax = axes[i // 5, i % 5]
    ax.axis('off')

    img = simages_vis[i].squeeze(0)
    ax.imshow(img, cmap='gray')
    ax.set_title(f"Pred: {spreds[i].item()}\nTrue: {slabels_vis[i].item()}") # .item() for scalar tensors

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()